### PR TITLE
made bill show page

### PR DESCRIPTION
**Pull request by JonathanTylerWeber**
Issue
-individual bill pages

Solution
-create routes and pages

Implementation Details
-I changed the session page to not use layout as discussed to avoid overlapping layouts. For the bill routes it actually made the most sense to me to use layout for this but maybe that's not the most optimal. The basic bill information is in the layout and then history, votes, and sponsors have separate pages. As for styling I didn't go too crazy as you mentioned we will likely get a designer but I made it fit with what we have and look alright.

Testing
-You can go through session bills and click on view bill to see the page. You can click through the tabs for history, votes, and sponsors. Not all bills have votes which is accounted for. There is currently a save button which doesn't do anything yet.

### CODE REVIEW

**Comment by JonathanTylerWeber** [comment]
I was running into issues changing file names and had to locally revert everything back a few times. I got it working but forgot to create a new branch again. Before pushing I thought it solved it by moving the changes to a new branch and everything looks right for this pr but locally now my files are a bit weird. Something may have happened so you can see if it's working for you here and if not I'll have to figure it out. After pushing it reverted some files locally.

**Comment by JonathanTylerWeber** [comment]
This should fix the issues I had when moving branches and work as expected.

**Comment by JonathanTylerWeber** [comment]
I also added a back button to session bills as clicking on the tabs are different routes so the browser back button won't lead directly back after clicking the tabs.

**Comment by JonathanTylerWeber** [comment]
We can probably rethink the wording for the links to the bill page and the legiscan link as both are view bill right now and I wasn't sure what else to call it for now.

**Comment by SevanBadal** [comment]
@JonathanTylerWeber looks good! I've created a `dev` branch. Let's merge into `dev` since the `save`  feature is not complete yet!

**Pull request merged**
